FROM cypress/included:13.10.0

RUN apt-get update && \
  apt-get install --no-install-recommends -y \
  curl \
  jq

ARG CYPRESS_RECORD_KEY
ENV CYPRESS_RECORD_KEY=$CYPRESS_RECORD_KEY
ARG CYPRESS_MLS_LIVE_KEY
ENV CYPRESS_MLS_LIVE_KEY=$CYPRESS_MLS_LIVE_KEY
ARG CYPRESS_NEXTPRO_LIVE_KEY
ENV CYPRESS_NEXTPRO_LIVE_KEY=$CYPRESS_NEXTPRO_LIVE_KEY
ARG CYPRESS_MLS_KEY
ENV CYPRESS_MLS_KEY=$CYPRESS_MLS_KEY
ARG CYPRESS_NEXTPRO_KEY
ENV CYPRESS_NEXTPRO_KEY=$CYPRESS_NEXTPRO_KEY
ARG CYPRESS_TEST_EMAIL
ENV CYPRESS_TEST_EMAIL=$CYPRESS_TEST_EMAIL
ARG CYPRESS_TEST_PASSWORD
ENV CYPRESS_TEST_PASSWORD=$CYPRESS_TEST_PASSWORD
ARG CYPRESS_TEST_USERNAME
ENV CYPRESS_TEST_USERNAME=$CYPRESS_TEST_USERNAME
ARG statsAPIToken
ENV statsAPIToken=$statsAPIToken

WORKDIR /root/cypress
COPY . .
RUN npm i 
ENTRYPOINT ["cypress", "run"]