export const teamNames = {
  // East teams:
  MIA: "Miami",
  DC: "D.C.",
  CLB: "Columbus",
  CLT: "Charlotte",
  PHI: "Philadelphia",
  CHI: "Chicago",
  MTL: "Montréal",
  RBNY: "New York",
  CIN: "Cincinnati",
  ORL: "Orlando",
  NSH: "Nashville",
  TOR: "Toronto",
  ATL: "Atlanta",
  NYC: "New York City",
  NE: "New England",
  // West teams:
  POR: "Portland",
  DAL: "Dallas",
  MIN: "Minnesota",
  LAFC: "LAFC",
  HOU: "Houston",
  SKC: "Kansas City",
  STL: "St. Louis",
  LA: "LA",
  RSL: "Salt Lake",
  VAN: "Vancouver",
  SEA: "Seattle",
  ATX: "Austin",
  SJ: "San Jose",
  COL: "Colorado"
};

export const expectedClubsFullNames = [
  "Atlanta United",
  "Austin FC",
  "Charlotte FC",
  "Chicago Fire FC",
  "FC Cincinnati",
  "Colorado Rapids",
  "Columbus Crew",
  "D.C. United",
  "FC Dallas",
  "Houston Dynamo FC",
  "Sporting Kansas City",
  "LA Galaxy",
  "Los Angeles Football Club",
  "Inter Miami CF",
  "Minnesota United",
  "CF Montréal",
  "Nashville SC",
  "New England Revolution",
  "New York Red Bulls",
  "New York City FC",
  "Orlando City",
  "Philadelphia Union",
  "Portland Timbers",
  "Real Salt Lake",
  "San Jose Earthquakes",
  "Seattle Sounders FC",
  "St. Louis CITY SC",
  "Toronto FC",
  "Vancouver Whitecaps FC",
  "San Diego FC"
];

export const allCompetitionsExpectedArr = [
  "All Competitions",
  "Regular Season",
  "U.S. Open Cup",
  "World Cup",
  "CCC",
  "MLS Cup Playoffs",
  "Gold Cup",
  "Campeones Cup",
  "Leagues Cup",
  "All-Star Game",
  "World Cup Qualifiers",
  "Canadian Champ",
  "Copa America",
  "Nations League",
  "Friendly"
];

export const allClubsExpectedArr = [
  "All Clubs",
  "Atlanta",
  "Austin",
  "Charlotte",
  "Chicago",
  "Cincinnati",
  "Colorado",
  "Columbus",
  "Dallas",
  "D.C.",
  "Houston",
  "Kansas City",
  "LA",
  "LAFC",
  "Miami",
  "Minnesota",
  "Montréal",
  "Nashville",
  "New England",
  "New York",
  "New York City",
  "Orlando",
  "Philadelphia",
  "Portland",
  "Salt Lake",
  "San Jose",
  "Seattle",
  "St. Louis",
  "Toronto",
  "Vancouver",
  "Canada",
  "United States"
];

export const allClubsExpectedArrLC = [
  "All Clubs",
  "América",
  "Atlanta",
  "Atlas",
  "Austin",
  "Charlotte",
  "Chicago",
  "Chivas",
  "Cincinnati",
  "Colorado",
  "Columbus",
  "Cruz Azul",
  "Dallas",
  "D.C.",
  "Houston",
  "Juárez",
  "Kansas City",
  "LA",
  "LAFC",
  "León",
  "Mazatlán",
  "Miami",
  "Minnesota",
  "Monterrey",
  "Montréal",
  "Nashville",
  "Necaxa",
  "New England",
  "New York",
  "New York City",
  "Orlando",
  "Pachuca",
  "Philadelphia",
  "Portland",
  "Puebla",
  "Pumas",
  "Querétaro",
  "Salt Lake",
  "San Jose",
  "San Luis",
  "Santos Laguna",
  "Seattle",
  "St. Louis",
  "Tigres",
  "Tijuana",
  "Toluca",
  "Toronto",
  "Vancouver"
];

export const clubs = [
  "Atlanta",
  "Austin",
  "Charlotte",
  "Chicago",
  "Cincinnati",
  "Colorado",
  "Columbus",
  "Dallas",
  "D.C.",
  "Houston",
  "Kansas City",
  "LA",
  "LAFC",
  "Miami",
  "Minnesota",
  "Montréal",
  "Nashville",
  "New England",
  "New York",
  "New York City",
  "Orlando",
  "Philadelphia",
  "Portland",
  "Salt Lake",
  "San Jose",
  "Seattle",
  "St. Louis",
  "Toronto",
  "Vancouver",
  "Canada",
  "United States"
];

export const nextProClubs = [
  "Philadelphia",
  "North Texas",
  "Chattanooga FC",
  "St Louis",
  "Ventura County",
  "LAFC",
  "SKCII",
  "Chicago",
  "Cincinnati",
  "Miami",
  "Tacoma",
  "Crown Legacy FC",
  "New York Red Bulls II",
  "NYCFC II",
  "Orlando",
  "Whitecaps FC 2",
  "Columbus",
  "Timbers2",
  "Town FC",
  "Toronto",
  "New England",
  "MNUFC2",
  "Atlanta",
  "Real Monarchs",
  "Houston",
  "Austin",
  "Colorado",
  "Carolina",
  "Huntsville"
];

export const optionalCompetitions = [
  "Major League Soccer - Regular Season",
  "Copa America",
  "Analysis Test",
  "German Bundesliga",
  "French Ligue 1",
  "Concacaf World Cup Qualifiers",
  "Club Friendly Matches",
  "Asian and North American World Cup Play-Off",
  "MLS All-Star Game",
  "Olympic Football Tournament",
  "Concacaf Gold Cup",
  "FIFA World Cup",
  "Women's World Cup",
  "Champions League",
  "CONCACAF Champions Cup",
  "Canadian Championship",
  "World Football Challenge",
  "U.S. Open Cup",
  "MLS Combine",
  "Olympic Women's Tournament",
  "Concacaf and Oceania World Cup Play-Off",
  "CONCACAF Cup",
  "Olympic Qualifying Playoff",
  "English Premier League",
  "USL Championship",
  "National Womens Soccer League",
  "Campeones Cup",
  "Intercontinental Cup (India)",
  "Concacaf Nations League Qualifiers",
  "Leagues Cup",
  "Concacaf Nations League",
  "MLS is Back Tournament Knockout Stage",
  "NWSL Fall Series",
  "Greek Cup",
  "MLS is Back Tournament Group Stage",
  "Russian Premier League",
  "Saudi Arabian Kings Cup",
  "Spanish La Liga",
  "English U18 Premier League",
  "Dutch KNVB Cup",
  "Saudi Arabian Professional League",
  "English Football League - League One",
  "English Football League - Championship",
  "Portuguese League Cup",
  "German Bundesliga (Sportec Data Official)",
  "Belgian Jupiler Pro League",
  "Spanish Segunda Division",
  "Mexican Primera (Clausura)",
  "Swedish Damallsvenskan",
  "English Football League - League Two",
  "Brazilian Serie B",
  "African Nations Championship",
  "Portuguese Primeira Liga",
  "English FA Trophy",
  "Croatia Prva HNL",
  "German 3rd Liga",
  "English FA Cup",
  "Romania Liga I",
  "Andorran First Division",
  "Mexican Primera (Apertura)",
  "Internationals Women",
  "Women's European Championship Qualifiers",
  "English Premier League 2 Division One",
  "CAF Champions League",
  "Indian Super League",
  "Turkish Super Lig",
  "English Premier League 2 Division Two",
  "Colombia Primera A Apertura",
  "Egyptian Premier League",
  "Olympic Tournament Qualifying Concacaf",
  "MLS NEXT Pro - Regular Season",
  "MLS NEXT Pro Invitational",
  "Other Club Friendlies",
  "FIFA Club World Cup",
  "Leagues Cup",
  "Internationals"
];

export const optionalClubs = [
  "Semi-Finalist 4",
  "Semi-Finalist 3",
  "Semi-Finalist 2",
  "Semi-Finalist 1",
  "Finalist 2",
  "Finalist 1",
  "TBC",
  "TBD Home",
  "TBD Away"
];

export const nameMapping = {
  "New York Red Bulls": "New York",
  "Sporting Kansas City": "Kansas City",
  "Colorado Rapids": "Colorado",
  "Columbus Crew": "Columbus",
  "New England Revolution": "New England",
  "San Jose Earthquakes": "San Jose",
  "Chicago Fire FC": "Chicago",
  "LA Galaxy": "LA",
  "D.C. United": "D.C.",
  "Portland Timbers": "Portland",
  "CF Montréal": "Montréal",
  "Vancouver Whitecaps FC": "Vancouver",
  "Houston Dynamo FC": "Houston",
  "Real Salt Lake": "Salt Lake",
  "FC Dallas": "Dallas",
  "Toronto FC": "Toronto",
  "Seattle Sounders FC": "Seattle",
  "Philadelphia Union": "Philadelphia",
  "Orlando City": "Orlando",
  "Minnesota United": "Minnesota",
  "New York City FC": "New York City",
  "Atlanta United": "Atlanta",
  "FC Cincinnati": "Cincinnati",
  "Los Angeles Football Club": "LAFC",
  "Inter Miami CF": "Miami",
  "Nashville SC": "Nashville",
  "Austin FC": "Austin",
  "Charlotte FC": "Charlotte",
  "St. Louis CITY SC": "St. Louis",
  "Canada": "Canada",
  "United States": "United States",
  "Semi-Finalist 4": "Semi-Finalist 4",
  "Semi-Finalist 3": "Semi-Finalist 3",
  "Semi-Finalist 2": "Semi-Finalist 2",
  "Semi-Finalist 1": "Semi-Finalist 1",
  "Finalist 2": "Finalist 2",
  "Finalist 1": "Finalist 1",
  "TBC": "TBC",
  "TBD Home": "TBD Home",
  "TBD Away": "TBD Away"
};

export const nextProClubsMapping = {
  "ATX": "Austin FC II",
  "ATL": "Atlanta United 2",
  "CFC": "Chattanooga FC",
  "CCFC": "Carolina Core FC",
  "CIN": "FC Cincinnati 2",
  "CHI": "Chicago Fire FC II",
  "CLB": "Columbus Crew 2",
  "CLFC": "Crown Legacy Football Club",
  "COL": "Colorado Rapids 2",
  "HOU": "Houston Dynamo 2",
  "MIN": "MNUFC2",
  "MIA": "Inter Miami CF II",
  "NE": "New England Revolution II",
  "NTX": "North Texas SC",
  "NYC": "NYCFC II",
  "ORL": "Orlando City B",
  "PHI": "Philadelphia Union II",
  "POR": "Timbers2",
  "RBNY": "New York Red Bulls II",
  "SLC": "Real Monarchs",
  "HNT": "Huntsville City Football Club",
  "SKC": "Sporting KC II",
  "TAC": "Tacoma Defiance",
  "TOR": "TFC II",
  "TTFC": "The Town FC",
  "VCFC": "Ventura County FC",
  "VAN": "Whitecaps FC 2",
  "STL": "St Louis CITY2",
  "LAFC": "Los Angeles Football Club 2",
};

// Commented ambiguous club names 
export const MLSClubMapping = {
  MIA: "Inter Miami CF",
  DC: "D.C. United",
  CLB: "Columbus Crew",
  CLT: "Charlotte FC",
  PHI: "Philadelphia Union",
  CHI: "Chicago Fire FC",
  MTL: "CF Montréal",
  RBNY: "New York Red Bulls",
  CIN: "FC Cincinnati",
  ORL: "Orlando City",
  NSH: "Nashville SC",
  TOR: "Toronto FC",
  ATL: "Atlanta United",
  NYC: "New York City FC",
  NE: "New England Revolution",
  POR: "Portland Timbers",
  DAL: "FC Dallas",
  MIN: "Minnesota United",
  LAFC: "Los Angeles Football Club",
  HOU: "Houston Dynamo FC",
  SKC: "Sporting Kansas City",
  STL: "St. Louis CITY SC",
  LA: "LA Galaxy",
  RSL: "Real Salt Lake",
  VAN: "Vancouver Whitecaps FC",
  SEA: "Seattle Sounders FC",
  ATX: "Austin FC",
  SJ: "San Jose Earthquakes",
  COL: "Colorado Rapids",
  "TBC": "TBC",
  "Semi-Finalist 1": "Semi-Finalist 1",
  "Semi-Finalist 2": "Semi-Finalist 2",
  "Semi-Finalist 3": "Semi-Finalist 3",
  "Semi-Finalist 4": "Semi-Finalist 4",
  "Finalist 1": "Finalist 1",
  "Finalist 2": "Finalist 2",
  "TBD Home": "TBD Home",
  "TBD Away": "TBD Away"
};

